# Generated by Django 4.2.7 on 2023-12-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_bankrupt_transaction_related_acount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='related_acount',
            new_name='related_account',
        ),
    ]
