# Generated by Django 4.2.7 on 2023-12-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_related_acount_transaction_related_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='related_account',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
