# Generated by Django 4.2.7 on 2023-12-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_related_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bankrupt',
        ),
    ]
